eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  servlet:
    multipart:
      max-file-size: 1024KB
      max-request-size: 1024KB
storage:
  path: "/home/dirceu/dev/docker_volumes/storage_service"
